/** *******************************************************************************************************************
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 ******************************************************************************************************************** */
import { readFileSync } from 'fs';
import { join } from 'path';
import { convertTmtThreats } from '.';
import { TemplateThreatStatement } from '../../../customTypes';
import { parseTmtModel } from '../parseTmtModel';
import { TMT_TEMPLATE_MAPPINGS } from '../templateMappings';
import { TmtModel, TmtThreat } from '../tmtModel';

const fixture = (name: string) => readFileSync(join(__dirname, '../__fixtures__', name), 'utf-8');

const meta = (threat: TemplateThreatStatement, key: string) => threat.metadata?.find((m) => m.key === key)?.value;

const makeThreat = (over: Partial<TmtThreat>): TmtThreat => ({ id: 1, key: 'k', properties: {}, ...over });
const makeModel = (over: Partial<TmtModel>): TmtModel => ({
  version: '4.3',
  metadata: {},
  surfaces: [],
  elementNames: {},
  threats: [],
  notes: [],
  knowledgeBase: { threatTypes: {}, propertyLabels: {} },
  ...over,
});

describe('convertTmtThreats - Sample_Threat_Model.tm7 (common path)', () => {
  const { threats, unconvertible, warnings } = convertTmtThreats(parseTmtModel(fixture('Sample_Threat_Model.tm7')));

  test('converts every threat with nothing unconvertible and no warnings', () => {
    expect(threats).toHaveLength(29);
    expect(unconvertible).toEqual([]);
    expect(warnings).toEqual([]);
  });

  test('composes a known threat from its curated mapping, with status, priority, STRIDE and custom metadata', () => {
    const threat = threats.find((t) => t.numericId === 7);
    expect(threat).toBeDefined();
    expect(threat?.id).toHaveLength(36);
    expect(threat).toMatchObject({
      threatSource: 'attacker',
      threatAction: 'spoof OS Process',
      threatImpact: 'information disclosure by Generic Data Store',
      impactedGoal: ['confidentiality'],
    });
    expect(threat?.customTemplate).toBeUndefined();
    expect(threat?.statement).toBe(
      'An attacker can spoof OS Process, which leads to information disclosure by Generic Data Store, resulting in reduced confidentiality',
    );
    expect(threat?.displayedStatement).toBeDefined();
    expect(threat?.status).toBe('threatIdentified');
    expect(meta(threat!, 'STRIDE')).toEqual(['S']);
    expect(meta(threat!, 'Priority')).toBe('High');
    expect(meta(threat!, 'custom:TMT Threat ID')).toBe('7');
    expect(meta(threat!, 'custom:TMT Title')).toBe('Spoofing the OS Process Process');
    expect(meta(threat!, 'custom:TMT State')).toBe('AutoGenerated');
    expect(meta(threat!, 'custom:TMT Category')).toBe('S');
  });
});

describe.each([
  ['Sample_Threat_Model.tm7', 29],
  ['Sample_Threat_Model_Multiple_DFDs.tm7', 87],
  ['ContosoCast Threat Model Fully Labeled with AI.tm7', 145],
])('convertTmtThreats - %s curated mappings', (name, count) => {
  test('composes every threat from a curated mapping, with no fallback', () => {
    const { threats, unconvertible, warnings } = convertTmtThreats(parseTmtModel(fixture(name)));
    expect(unconvertible).toEqual([]);
    expect(warnings.filter((w) => w.includes('curated template mapping'))).toEqual([]);
    expect(threats).toHaveLength(count);
    expect(threats.filter((t) => !t.threatSource || !t.threatAction || t.customTemplate)).toEqual([]);
  });
});

const mappingFor = (id: string) => TMT_TEMPLATE_MAPPINGS.find((m) => m.id === id)!;
const fill = (text: string, names: Record<string, string>) =>
  text.replace(/\{(source|target|flow)\.Name\}/g, (_m, role: string) => names[role]);

describe('convertTmtThreats - curated mapping rules', () => {
  const names = { source: 'Web App', target: 'Orders DB', flow: 'HTTPS' };
  const elementModel = (threat: TmtThreat, elementNames: Record<string, string> = { s: names.source, t: names.target, f: names.flow }) =>
    makeModel({ elementNames, threats: [{ ...threat, sourceGuid: 's', targetGuid: 't', flowGuid: 'f' }] });

  test('fills a lowercase placeholder that TMT left unfilled in the description', () => {
    const i23 = mappingFor('I23');
    const { threats, warnings } = convertTmtThreats(elementModel(makeThreat({
      typeId: 'I23', properties: { Title: i23.title, UserThreatDescription: i23.template },
    })));
    expect(warnings).toEqual([]);
    expect(threats[0].prerequisites).toBe('who can take advantage of improper data protection of Web App');
  });

  test('falls back to the description, with a warning, when the description was edited', () => {
    const s2 = mappingFor('S2');
    const { threats, warnings } = convertTmtThreats(elementModel(makeThreat({
      typeId: 'S2', properties: { Title: fill(s2.title, names), UserThreatDescription: 'Orders DB can be spoofed.' },
    })));
    expect(threats[0]).toMatchObject({ threatAction: 'Orders DB can be spoofed.', customTemplate: '[threat_action]', statement: 'Orders DB can be spoofed.' });
    expect(warnings).toEqual(['TMT threat 1: no curated template mapping matched its title and description, so its statement is the TMT description as written']);
  });

  test('falls back to the title when the description is over the field limit', () => {
    const { threats, warnings } = convertTmtThreats(makeModel({
      threats: [makeThreat({ properties: { Title: 'Short title', UserThreatDescription: 'd'.repeat(201) } })],
    }));
    expect(threats[0].threatAction).toBe('Short title');
    expect(warnings[0]).toContain('statement is the TMT title as written');
  });

  test('falls back, with a warning, when a mapped field would exceed the field limit', () => {
    const e7 = mappingFor('E7');
    const longNames = { ...names, target: 'T'.repeat(150) };
    const { threats, warnings } = convertTmtThreats(elementModel(makeThreat({
      typeId: 'E7', properties: { Title: fill(e7.title, longNames), UserThreatDescription: fill(e7.template, longNames) },
    }), { s: longNames.source, t: longNames.target, f: longNames.flow }));
    expect(threats[0].threatAction).toBe(fill(e7.title, longNames));
    expect(warnings).toEqual(['TMT threat 1: its curated template mapping exceeded a Threat Composer field limit, so its statement is the TMT title as written']);
  });

  test('does not apply a mapping when a placeholder\'s element has no name', () => {
    const s2 = mappingFor('S2');
    const { threats, unconvertible } = convertTmtThreats(elementModel(makeThreat({
      typeId: 'S2', properties: { Title: s2.title, UserThreatDescription: s2.template },
    }), {}));
    expect(threats).toEqual([]);
    expect(unconvertible).toEqual([{ id: 1, reason: expect.stringContaining('No usable threat statement') }]);
  });
});

describe('convertTmtThreats - hostile input', () => {
  const s2 = mappingFor('S2');
  const withElements = (threat: TmtThreat, elementNames: Record<string, string>) =>
    makeModel({ elementNames, threats: [{ ...threat, sourceGuid: 's', targetGuid: 't', flowGuid: 'f' }] });

  test('rejects a threat that refers to an element name over 200 characters, quickly', () => {
    const huge = 'N'.repeat(1024 * 1024);
    const started = Date.now();
    const { threats, unconvertible } = convertTmtThreats(withElements(makeThreat({
      typeId: 'S2', properties: { Title: fill(s2.title, { target: huge }), UserThreatDescription: fill(s2.template, { source: 'Web App', target: huge }) },
    }), { s: 'Web App', t: huge }));
    expect(Date.now() - started).toBeLessThan(2000);
    expect(threats).toEqual([]);
    expect(unconvertible).toEqual([{ id: 1, reason: 'No usable threat statement: a diagram element name it refers to exceeds 200 characters.' }]);
  });

  test('does not expand a description full of placeholders', () => {
    const started = Date.now();
    const { threats, warnings } = convertTmtThreats(withElements(makeThreat({
      properties: { Title: 'Short title', UserThreatDescription: '{source.Name} '.repeat(5000) },
    }), { s: 'N'.repeat(199) }));
    expect(Date.now() - started).toBeLessThan(2000);
    expect(threats[0].threatAction).toBe('Short title');
    expect(warnings[0]).toContain('statement is the TMT title as written');
  });

  test('matches element names containing regex characters only literally', () => {
    const names = { source: 'Web App', target: 'a.*' };
    const literal = convertTmtThreats(withElements(makeThreat({
      typeId: 'S2', properties: { Title: fill(s2.title, names), UserThreatDescription: fill(s2.template, names) },
    }), { s: names.source, t: names.target }));
    expect(literal.threats[0].threatAction).toBe('spoof a.*');
    expect(literal.warnings).toEqual([]);

    const other = { source: 'Web App', target: 'aXYZ' };
    const wildcard = convertTmtThreats(withElements(makeThreat({
      typeId: 'S2', properties: { Title: fill(s2.title, other), UserThreatDescription: fill(s2.template, other) },
    }), { s: names.source, t: names.target }));
    expect(wildcard.warnings[0]).toContain('no curated template mapping matched');
  });

  test('measures fallback text after HTML encoding, so an \'&\' near the limit falls through', () => {
    const description = `${'d'.repeat(195)} & e`;
    expect(description).toHaveLength(199);
    const { threats, unconvertible, warnings } = convertTmtThreats(makeModel({
      threats: [makeThreat({ properties: { Title: 'Short title', UserThreatDescription: description } })],
    }));
    expect(unconvertible).toEqual([]);
    expect(threats[0].threatAction).toBe('Short title');
    expect(warnings[0]).toContain('statement is the TMT title as written');
  });

  test('treats inherited object member names as unknown state and priority', () => {
    const { threats, warnings } = convertTmtThreats(makeModel({
      threats: [makeThreat({ state: 'constructor', priority: 'toString', properties: { Title: 'a' } })],
    }));
    expect(threats[0].status).toBe('threatIdentified');
    expect(meta(threats[0], 'Priority')).toBeUndefined();
    expect(warnings).toContain("Unknown TMT state 'constructor' for threat 1; defaulted to identified");
  });
});

describe('convertTmtThreats - status mapping', () => {
  const model = makeModel({
    knowledgeBase: { threatTypes: { TT: { id: 'TT', category: 'S' } }, propertyLabels: {} },
    threats: [
      makeThreat({ id: 1, typeId: 'TT', state: 'Mitigated', properties: { Title: 'a' } }),
      makeThreat({ id: 2, typeId: 'TT', state: 'NotApplicable', properties: { Title: 'b' } }),
      makeThreat({ id: 3, typeId: 'TT', state: 'NeedsInvestigation', properties: { Title: 'c' } }),
      makeThreat({ id: 4, typeId: 'TT', state: 'Migrated', properties: { Title: 'd' } }),
    ],
  });
  const { threats } = convertTmtThreats(model);

  test('maps TMT states to TC statuses', () => {
    expect(threats.map((t) => t.status)).toEqual([
      'threatResolved',
      'threatResolvedNotUseful',
      'threatIdentified',
      'threatIdentified',
    ]);
  });

  test('defaults an unknown state to identified and warns', () => {
    const unknownStateModel = makeModel({
      threats: [makeThreat({ id: 1, state: 'Bogus', properties: { Title: 'a' } })],
    });
    const result = convertTmtThreats(unknownStateModel);
    expect(result.threats[0].status).toBe('threatIdentified');
    expect(result.warnings.join(' ')).toContain("Unknown TMT state 'Bogus'");
  });
});

describe('convertTmtThreats - statement resolution', () => {
  test('falls back to a placeholder-free ShortTitle when Title is absent', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: { TT: { id: 'TT', shortTitle: 'Generic spoofing threat' } }, propertyLabels: {} },
      threats: [makeThreat({ id: 1, typeId: 'TT', properties: {} })],
    });
    expect(convertTmtThreats(model).threats[0].statement).toBe('Generic spoofing threat');
  });

  test('surfaces (does not throw) a threat with neither a Title nor a resolvable ShortTitle', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: { TT: { id: 'TT', shortTitle: 'Spoofing the {target.Name} Process' } }, propertyLabels: {} },
      threats: [makeThreat({ id: 7, typeId: 'TT', properties: {} })],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(threats).toEqual([]);
    expect(unconvertible).toEqual([{ id: 7, reason: expect.stringContaining('No usable threat statement') }]);
  });
});

describe('convertTmtThreats - over-length fields are surfaced, not truncated', () => {
  test('surfaces a threat whose only text is over the statement field limit', () => {
    const model = makeModel({
      threats: [
        makeThreat({ id: 1, properties: { Title: 'x'.repeat(201) } }),
        makeThreat({ id: 2, properties: { Title: 'ok' } }),
      ],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(threats.map((t) => t.numericId)).toEqual([2]);
    expect(unconvertible).toEqual([{ id: 1, reason: expect.stringContaining('over the 200-character field limit') }]);
  });

  test('surfaces a threat whose custom metadata field name exceeds the key limit', () => {
    const longLabel = 'L'.repeat(60); // 'custom:TMT ' + 60 chars > 50
    const model = makeModel({
      knowledgeBase: { threatTypes: {}, propertyLabels: { Foo: longLabel } },
      threats: [makeThreat({ id: 1, properties: { Title: 'a', Foo: 'bar' } })],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(threats).toEqual([]);
    expect(unconvertible).toEqual([{ id: 1, reason: expect.stringContaining('exceeding the 50-character limit') }]);
  });

  test('keeps a custom metadata value at the value limit without truncation', () => {
    const longValue = 'v'.repeat(100000);
    const model = makeModel({
      knowledgeBase: { threatTypes: {}, propertyLabels: { Foo: 'Foo Label' } },
      threats: [makeThreat({ id: 1, properties: { Title: 'a', Foo: longValue } })],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(unconvertible).toEqual([]);
    expect(meta(threats[0], 'custom:TMT Foo Label')).toBe(longValue);
  });

  test('surfaces a threat whose custom metadata value exceeds the value limit', () => {
    const model = makeModel({
      threats: [
        makeThreat({ id: 1, properties: { Title: 'a', Foo: 'v'.repeat(100001) } }),
        makeThreat({ id: 2, properties: { Title: 'ok' } }),
      ],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(threats.map((t) => t.numericId)).toEqual([2]);
    expect(unconvertible).toEqual([{
      id: 1,
      reason: 'Metadata field "custom:TMT Foo" value is 100001 characters, exceeding the 100000-character limit.',
    }]);
  });

  test('surfaces a threat with more metadata fields than the field limit', () => {
    const properties = (count: number) => Object.fromEntries([
      ['Title', 'a'],
      ...Array.from({ length: count }, (_, i) => [`P${i}`, 'v']),
    ]);
    // Each threat also gets 'custom:TMT Threat ID' and 'custom:TMT Title', so N extra properties yield N + 2 fields.
    const model = makeModel({
      threats: [
        makeThreat({ id: 1, properties: properties(48) }),
        makeThreat({ id: 2, properties: properties(49) }),
      ],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(threats.map((t) => t.metadata?.length)).toEqual([50]);
    expect(unconvertible).toEqual([{ id: 2, reason: 'Threat has 51 metadata fields, exceeding the 50-field limit.' }]);
  });
});

describe('convertTmtThreats - metadata edge cases', () => {
  test('omits STRIDE and warns for a non-STRIDE category, but preserves custom:TMT Category', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: { TT: { id: 'TT', category: 'Custom' } }, propertyLabels: {} },
      threats: [makeThreat({ id: 1, typeId: 'TT', properties: { Title: 'a' } })],
    });
    const { threats, warnings } = convertTmtThreats(model);
    expect(meta(threats[0], 'STRIDE')).toBeUndefined();
    expect(meta(threats[0], 'custom:TMT Category')).toBe('Custom');
    expect(warnings.join(' ')).toContain('not a STRIDE letter');
  });

  test('omits Priority for an unrecognized priority value', () => {
    const model = makeModel({ threats: [makeThreat({ id: 1, priority: 'Critical', properties: { Title: 'a' } })] });
    expect(meta(convertTmtThreats(model).threats[0], 'Priority')).toBeUndefined();
  });

  test('preserves every other property as custom:TMT <label>, using the KB label', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: {}, propertyLabels: { Foo: 'Foo Label' } },
      threats: [makeThreat({ id: 1, properties: { Title: 'a', Foo: 'bar' } })],
    });
    expect(meta(convertTmtThreats(model).threats[0], 'custom:TMT Foo Label')).toBe('bar');
  });

  test('appends the raw property name when a label collides with a fixed custom entry', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: { TT: { id: 'TT', category: 'S' } }, propertyLabels: { UserThreatCategory: 'Category' } },
      threats: [makeThreat({ id: 1, typeId: 'TT', properties: { Title: 'a', UserThreatCategory: 'orig-cat' } })],
    });
    const threat = convertTmtThreats(model).threats[0];
    expect(meta(threat, 'custom:TMT Category')).toBe('S');
    expect(meta(threat, 'custom:TMT UserThreatCategory')).toBe('orig-cat');
  });
});

describe('convertTmtThreats - numeric id policy', () => {
  test('reassigns a duplicate numericId and warns', () => {
    const model = makeModel({
      threats: [
        makeThreat({ id: 5, properties: { Title: 'a' } }),
        makeThreat({ id: 5, properties: { Title: 'b' } }),
      ],
    });
    const { threats, warnings } = convertTmtThreats(model);
    expect(threats[0].numericId).toBe(5);
    expect(threats[1].numericId).not.toBe(5);
    expect(meta(threats[1], 'custom:TMT Threat ID')).toBe('5'); // original id preserved
    expect(warnings.join(' ')).toContain('Duplicate TMT threat id 5');
  });
});
