/** *******************************************************************************************************************
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 ******************************************************************************************************************** */
import { readFileSync } from 'fs';
import { join } from 'path';
import { convertTmtThreats } from '.';
import { TemplateThreatStatement } from '../../../customTypes';
import { parseTmtModel } from '../parseTmtModel';
import { TmtModel, TmtThreat } from '../tmtModel';

const fixture = (name: string) => readFileSync(join(__dirname, '../__fixtures__', name), 'utf-8');

const meta = (threat: TemplateThreatStatement, key: string) => threat.metadata?.find((m) => m.key === key)?.value;

const makeThreat = (over: Partial<TmtThreat>): TmtThreat => ({ id: 1, key: 'k', properties: {}, ...over });
const makeModel = (over: Partial<TmtModel>): TmtModel => ({
  version: '4.3',
  metadata: {},
  surfaces: [],
  threats: [],
  notes: [],
  knowledgeBase: { threatTypes: {}, propertyLabels: {} },
  ...over,
});

describe('convertTmtThreats - Sample_Threat_Model.tm7 (common path)', () => {
  const { threats, unconvertible, warnings } = convertTmtThreats(parseTmtModel(fixture('Sample_Threat_Model.tm7')));

  test('converts every threat with nothing unconvertible and no warnings', () => {
    expect(threats).toHaveLength(29);
    expect(unconvertible).toEqual([]);
    expect(warnings).toEqual([]);
  });

  test('maps a known threat verbatim, with status, priority, STRIDE and custom metadata', () => {
    const threat = threats.find((t) => t.numericId === 7);
    expect(threat).toBeDefined();
    expect(threat?.id).toHaveLength(36);
    expect(threat?.statement).toBe('Spoofing the OS Process Process');
    expect(threat?.status).toBe('threatIdentified');
    expect(meta(threat!, 'STRIDE')).toEqual(['S']);
    expect(meta(threat!, 'Priority')).toBe('High');
    expect(meta(threat!, 'custom:TMT Threat ID')).toBe('7');
    expect(meta(threat!, 'custom:TMT State')).toBe('AutoGenerated');
    expect(meta(threat!, 'custom:TMT Category')).toBe('S');
  });
});

describe('convertTmtThreats - status mapping', () => {
  const model = makeModel({
    knowledgeBase: { threatTypes: { TT: { id: 'TT', category: 'S' } }, propertyLabels: {} },
    threats: [
      makeThreat({ id: 1, typeId: 'TT', state: 'Mitigated', properties: { Title: 'a' } }),
      makeThreat({ id: 2, typeId: 'TT', state: 'NotApplicable', properties: { Title: 'b' } }),
      makeThreat({ id: 3, typeId: 'TT', state: 'NeedsInvestigation', properties: { Title: 'c' } }),
      makeThreat({ id: 4, typeId: 'TT', state: 'Migrated', properties: { Title: 'd' } }),
    ],
  });
  const { threats } = convertTmtThreats(model);

  test('maps TMT states to TC statuses', () => {
    expect(threats.map((t) => t.status)).toEqual([
      'threatResolved',
      'threatResolvedNotUseful',
      'threatIdentified',
      'threatIdentified',
    ]);
  });

  test('defaults an unknown state to identified and warns', () => {
    const unknownStateModel = makeModel({
      threats: [makeThreat({ id: 1, state: 'Bogus', properties: { Title: 'a' } })],
    });
    const result = convertTmtThreats(unknownStateModel);
    expect(result.threats[0].status).toBe('threatIdentified');
    expect(result.warnings.join(' ')).toContain("Unknown TMT state 'Bogus'");
  });
});

describe('convertTmtThreats - statement resolution', () => {
  test('falls back to a placeholder-free ShortTitle when Title is absent', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: { TT: { id: 'TT', shortTitle: 'Generic spoofing threat' } }, propertyLabels: {} },
      threats: [makeThreat({ id: 1, typeId: 'TT', properties: {} })],
    });
    expect(convertTmtThreats(model).threats[0].statement).toBe('Generic spoofing threat');
  });

  test('surfaces (does not throw) a threat with neither a Title nor a resolvable ShortTitle', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: { TT: { id: 'TT', shortTitle: 'Spoofing the {target.Name} Process' } }, propertyLabels: {} },
      threats: [makeThreat({ id: 7, typeId: 'TT', properties: {} })],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(threats).toEqual([]);
    expect(unconvertible).toEqual([{ id: 7, reason: expect.stringContaining('No resolvable threat statement') }]);
  });
});

describe('convertTmtThreats - over-length fields are surfaced, not truncated', () => {
  test('surfaces a threat whose statement exceeds the Threat Composer limit', () => {
    const model = makeModel({
      threats: [
        makeThreat({ id: 1, properties: { Title: 'x'.repeat(1401) } }),
        makeThreat({ id: 2, properties: { Title: 'ok' } }),
      ],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(threats.map((t) => t.numericId)).toEqual([2]);
    expect(unconvertible).toEqual([{ id: 1, reason: expect.stringContaining('exceeding the 1400-character limit') }]);
  });

  test('surfaces a threat whose custom metadata field name exceeds the key limit', () => {
    const longLabel = 'L'.repeat(60); // 'custom:TMT ' + 60 chars > 50
    const model = makeModel({
      knowledgeBase: { threatTypes: {}, propertyLabels: { Foo: longLabel } },
      threats: [makeThreat({ id: 1, properties: { Title: 'a', Foo: 'bar' } })],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(threats).toEqual([]);
    expect(unconvertible).toEqual([{ id: 1, reason: expect.stringContaining('exceeding the 50-character limit') }]);
  });

  test('keeps an unbounded custom metadata value without truncation', () => {
    const longValue = 'v'.repeat(5000);
    const model = makeModel({
      knowledgeBase: { threatTypes: {}, propertyLabels: { Foo: 'Foo Label' } },
      threats: [makeThreat({ id: 1, properties: { Title: 'a', Foo: longValue } })],
    });
    const { threats, unconvertible } = convertTmtThreats(model);
    expect(unconvertible).toEqual([]);
    expect(meta(threats[0], 'custom:TMT Foo Label')).toBe(longValue);
  });
});

describe('convertTmtThreats - metadata edge cases', () => {
  test('omits STRIDE and warns for a non-STRIDE category, but preserves custom:TMT Category', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: { TT: { id: 'TT', category: 'Custom' } }, propertyLabels: {} },
      threats: [makeThreat({ id: 1, typeId: 'TT', properties: { Title: 'a' } })],
    });
    const { threats, warnings } = convertTmtThreats(model);
    expect(meta(threats[0], 'STRIDE')).toBeUndefined();
    expect(meta(threats[0], 'custom:TMT Category')).toBe('Custom');
    expect(warnings.join(' ')).toContain('not a STRIDE letter');
  });

  test('omits Priority for an unrecognized priority value', () => {
    const model = makeModel({ threats: [makeThreat({ id: 1, priority: 'Critical', properties: { Title: 'a' } })] });
    expect(meta(convertTmtThreats(model).threats[0], 'Priority')).toBeUndefined();
  });

  test('preserves every other property as custom:TMT <label>, using the KB label', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: {}, propertyLabels: { Foo: 'Foo Label' } },
      threats: [makeThreat({ id: 1, properties: { Title: 'a', Foo: 'bar' } })],
    });
    expect(meta(convertTmtThreats(model).threats[0], 'custom:TMT Foo Label')).toBe('bar');
  });

  test('appends the raw property name when a label collides with a fixed custom entry', () => {
    const model = makeModel({
      knowledgeBase: { threatTypes: { TT: { id: 'TT', category: 'S' } }, propertyLabels: { UserThreatCategory: 'Category' } },
      threats: [makeThreat({ id: 1, typeId: 'TT', properties: { Title: 'a', UserThreatCategory: 'orig-cat' } })],
    });
    const threat = convertTmtThreats(model).threats[0];
    expect(meta(threat, 'custom:TMT Category')).toBe('S');
    expect(meta(threat, 'custom:TMT UserThreatCategory')).toBe('orig-cat');
  });
});

describe('convertTmtThreats - numeric id policy', () => {
  test('reassigns a duplicate numericId and warns', () => {
    const model = makeModel({
      threats: [
        makeThreat({ id: 5, properties: { Title: 'a' } }),
        makeThreat({ id: 5, properties: { Title: 'b' } }),
      ],
    });
    const { threats, warnings } = convertTmtThreats(model);
    expect(threats[0].numericId).toBe(5);
    expect(threats[1].numericId).not.toBe(5);
    expect(meta(threats[1], 'custom:TMT Threat ID')).toBe('5'); // original id preserved
    expect(warnings.join(' ')).toContain('Duplicate TMT threat id 5');
  });
});
