/** *******************************************************************************************************************
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 ******************************************************************************************************************** */
import {
  LEVEL_HIGH,
  LEVEL_LOW,
  LEVEL_MEDIUM,
  METADATA_KEY_PRIORITY,
  METADATA_KEY_STRIDE,
  SINGLE_FIELD_INPUT_MAX_LENGTH,
  SINGLE_FIELD_INPUT_SMALL_MAX_LENGTH,
  THREAT_STATUS_IDENTIFIED,
  THREAT_STATUS_NOT_USEFUL,
  THREAT_STATUS_RESOLVED,
} from '../../../configs';
import { TemplateThreatStatement, TemplateThreatStatementSchema } from '../../../customTypes';
import { TmtModel, TmtThreat, TmtThreatType } from '../tmtModel';

type MetadataEntry = { key: string; value: string | string[] };

/** A TMT threat that could not be faithfully imported. Reported to the user for an abort/ignore decision. */
export interface TmtUnconvertibleThreat {
  id: number;
  reason: string;
}

export interface TmtThreatConversionResult {
  threats: TemplateThreatStatement[];
  unconvertible: TmtUnconvertibleThreat[];
  warnings: string[];
}

// Mirror the Threat Composer schema caps so we can report an over-length field as a clear, specific
// reason rather than let strict schema validation fail the record generically. Kept in sync with
// TemplateThreatStatementSchema.statement and the custom-metadata key cap in MetadataSchemaThreats.
const STATEMENT_MAX_LENGTH = SINGLE_FIELD_INPUT_MAX_LENGTH * 7;
const METADATA_KEY_MAX_LENGTH = SINGLE_FIELD_INPUT_SMALL_MAX_LENGTH;

const STATUS_BY_STATE: Record<string, string> = {
  Mitigated: THREAT_STATUS_RESOLVED,
  NotApplicable: THREAT_STATUS_NOT_USEFUL,
  AutoGenerated: THREAT_STATUS_IDENTIFIED,
  Migrated: THREAT_STATUS_IDENTIFIED,
  NeedsInvestigation: THREAT_STATUS_IDENTIFIED,
  NeedsMitigation: THREAT_STATUS_IDENTIFIED,
};

const PRIORITY_BY_TMT: Record<string, string> = {
  High: LEVEL_HIGH,
  Medium: LEVEL_MEDIUM,
  Low: LEVEL_LOW,
};

const STRIDE_LETTERS = new Set(['S', 'T', 'R', 'I', 'D', 'E']);
const UNRESOLVED_PLACEHOLDER = /\{[^}]+\}/;

// Threat properties consumed by dedicated mappings below, so they are not repeated as custom:TMT <label>.
const CONSUMED_PROPERTIES = new Set(['Title', 'UserThreatDescription', 'InteractionString', 'StateInformation', 'Priority']);

// The statement is TMT's resolved title verbatim; fall back to the threat-type ShortTitle when absent.
// Placeholders ({source.Name} etc.) can't be resolved without DFD element labels (not extracted), so a
// ShortTitle that still contains placeholders yields no statement and blocks the import.
const resolveStatement = (threat: TmtThreat, threatType?: TmtThreatType): string | undefined => {
  const title = threat.properties.Title?.trim();
  if (title) {
    return title;
  }
  const shortTitle = threatType?.shortTitle?.trim();
  if (shortTitle && !UNRESOLVED_PLACEHOLDER.test(shortTitle)) {
    return shortTitle;
  }
  return undefined;
};

/**
 * Converts the threats of a parsed TMT model into Threat Composer threats, following the documented
 * '.tm7' -> Threat Composer mapping. A threat that cannot be faithfully imported (no resolvable
 * statement, or a field that would exceed a Threat Composer schema limit) is not silently dropped or
 * truncated: it is collected in 'unconvertible' with a clear reason for the import flow to present as
 * an abort/ignore decision. Softer issues (unknown state, non-STRIDE category, duplicate id) are
 * returned as non-blocking warnings on the threats that were converted.
 */
export const convertTmtThreats = (model: TmtModel): TmtThreatConversionResult => {
  const warnings: string[] = [];
  const unconvertible: TmtUnconvertibleThreat[] = [];
  const threats: TemplateThreatStatement[] = [];
  const surfaceNameByGuid = new Map(model.surfaces.map((surface) => [surface.guid, surface.name]));
  const usedNumericIds = new Set<number>();
  let nextAllocatedId = model.threats.reduce((max, threat) => Math.max(max, threat.id), 0) + 1;

  for (const threat of model.threats) {
    const threatType = threat.typeId ? model.knowledgeBase.threatTypes[threat.typeId] : undefined;

    const statement = resolveStatement(threat, threatType);
    if (!statement) {
      unconvertible.push({
        id: threat.id,
        reason: 'No resolvable threat statement: the threat has no Title and no placeholder-free short title.',
      });
      continue;
    }
    if (statement.length > STATEMENT_MAX_LENGTH) {
      unconvertible.push({
        id: threat.id,
        reason: `Threat statement is ${statement.length} characters, exceeding the ${STATEMENT_MAX_LENGTH}-character limit.`,
      });
      continue;
    }

    // Warnings gathered while building this threat are only committed if the threat is convertible.
    const threatWarnings: string[] = [];

    let status = THREAT_STATUS_IDENTIFIED;
    if (threat.state) {
      const mapped = STATUS_BY_STATE[threat.state];
      if (mapped) {
        status = mapped;
      } else {
        threatWarnings.push(`Unknown TMT state '${threat.state}' for threat ${threat.id}; defaulted to identified`);
      }
    }

    const metadata: MetadataEntry[] = [];
    const usedKeys = new Set<string>();
    const add = (key: string, value: string | string[] | undefined) => {
      if (value === undefined || value === '' || (Array.isArray(value) && value.length === 0) || usedKeys.has(key)) {
        return;
      }
      metadata.push({ key, value });
      usedKeys.add(key);
    };

    const category = threatType?.category?.trim();
    if (category && STRIDE_LETTERS.has(category)) {
      add(METADATA_KEY_STRIDE, [category]);
    } else if (category) {
      threatWarnings.push(`TMT category '${category}' for threat ${threat.id} is not a STRIDE letter; STRIDE omitted`);
    }

    if (threat.priority && PRIORITY_BY_TMT[threat.priority]) {
      add(METADATA_KEY_PRIORITY, PRIORITY_BY_TMT[threat.priority]);
    }

    add('custom:TMT Threat ID', String(threat.id));
    add('custom:TMT Category', category);
    add('custom:TMT State', threat.state);
    add('custom:TMT Description', threat.properties.UserThreatDescription);
    add('custom:TMT Interaction', threat.properties.InteractionString);
    add('custom:TMT Diagram', threat.drawingSurfaceGuid ? surfaceNameByGuid.get(threat.drawingSurfaceGuid) : undefined);
    add('custom:TMT Justification', threat.properties.StateInformation);

    // Preserve every other non-empty property as custom:TMT <label> (KB label, else raw name);
    // on collision with an existing key, fall back to the raw property name to stay unique.
    for (const [name, value] of Object.entries(threat.properties)) {
      if (CONSUMED_PROPERTIES.has(name) || !value) {
        continue;
      }
      const labelKey = `custom:TMT ${model.knowledgeBase.propertyLabels[name] ?? name}`;
      add(usedKeys.has(labelKey) ? `custom:TMT ${name}` : labelKey, value);
    }

    const overLongKey = metadata.find((entry) => entry.key.length > METADATA_KEY_MAX_LENGTH);
    if (overLongKey) {
      unconvertible.push({
        id: threat.id,
        reason: `Metadata field name "${overLongKey.key}" is ${overLongKey.key.length} characters, exceeding the ${METADATA_KEY_MAX_LENGTH}-character limit.`,
      });
      continue;
    }

    let numericId = threat.id;
    if (usedNumericIds.has(numericId)) {
      numericId = nextAllocatedId;
      nextAllocatedId += 1;
      threatWarnings.push(`Duplicate TMT threat id ${threat.id}; assigned numeric id ${numericId}`);
    }

    const candidate: TemplateThreatStatement = {
      id: crypto.randomUUID(),
      numericId,
      statement,
      status,
      metadata,
    };

    // Defensive check: any remaining schema violation reports this threat instead of failing the whole batch.
    const parsed = TemplateThreatStatementSchema.safeParse(candidate);
    if (!parsed.success) {
      unconvertible.push({
        id: threat.id,
        reason: `Does not satisfy the Threat Composer threat schema: ${parsed.error.issues
          .map((issue) => `${issue.path.join('.') || 'value'}: ${issue.message}`)
          .join('; ')}.`,
      });
      continue;
    }

    usedNumericIds.add(numericId);
    threats.push(candidate);
    warnings.push(...threatWarnings);
  }

  return { threats, unconvertible, warnings };
};
