/** *******************************************************************************************************************
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 ******************************************************************************************************************** */
import {
  LEVEL_HIGH,
  LEVEL_LOW,
  LEVEL_MEDIUM,
  METADATA_KEY_PRIORITY,
  METADATA_KEY_STRIDE,
  FREE_TEXT_INPUT_MAX_LENGTH,
  SINGLE_FIELD_INPUT_MAX_LENGTH,
  SINGLE_FIELD_INPUT_SMALL_MAX_LENGTH,
  THREAT_STATUS_IDENTIFIED,
  THREAT_STATUS_NOT_USEFUL,
  THREAT_STATUS_RESOLVED,
} from '../../../configs';
import { TemplateThreatStatement, TemplateThreatStatementSchema } from '../../../customTypes';
import renderThreatStatement from '../../renderThreatStatement';
import sanitizeHtml from '../../sanitizeHtml';
import { TMT_TEMPLATE_MAPPINGS, TmtTemplateFields } from '../templateMappings';
import { TmtModel, TmtThreat, TmtThreatType } from '../tmtModel';

type MetadataEntry = { key: string; value: string | string[] };

/** A TMT threat that could not be faithfully imported. Reported to the user for an abort/ignore decision. */
export interface TmtUnconvertibleThreat {
  id: number;
  reason: string;
}

export interface TmtThreatConversionResult {
  threats: TemplateThreatStatement[];
  unconvertible: TmtUnconvertibleThreat[];
  warnings: string[];
}

// Mirror the Threat Composer schema caps so we can report an over-length field as a clear, specific
// reason rather than let strict schema validation fail the record generically. Kept in sync with
// TemplateThreatStatementSchema.statement and the custom-metadata key cap in MetadataSchemaThreats.
const STATEMENT_MAX_LENGTH = SINGLE_FIELD_INPUT_MAX_LENGTH * 7;
const METADATA_KEY_MAX_LENGTH = SINGLE_FIELD_INPUT_SMALL_MAX_LENGTH;

// Not schema caps: bound untrusted input so a crafted file cannot stall rendering. Real threats carry at most ~15 entries.
const METADATA_VALUE_MAX_LENGTH = FREE_TEXT_INPUT_MAX_LENGTH;
const METADATA_MAX_ENTRIES = 50;

const longestValueLength = (entry: MetadataEntry) =>
  Math.max(...(Array.isArray(entry.value) ? entry.value : [entry.value]).map((v) => v.length));

const STATUS_BY_STATE = new Map<string, string>([
  ['Mitigated', THREAT_STATUS_RESOLVED],
  ['NotApplicable', THREAT_STATUS_NOT_USEFUL],
  ['AutoGenerated', THREAT_STATUS_IDENTIFIED],
  ['Migrated', THREAT_STATUS_IDENTIFIED],
  ['NeedsInvestigation', THREAT_STATUS_IDENTIFIED],
  ['NeedsMitigation', THREAT_STATUS_IDENTIFIED],
]);

const PRIORITY_BY_TMT = new Map<string, string>([
  ['High', LEVEL_HIGH],
  ['Medium', LEVEL_MEDIUM],
  ['Low', LEVEL_LOW],
]);

const STRIDE_LETTERS = new Set(['S', 'T', 'R', 'I', 'D', 'E']);

// Threat properties consumed by dedicated mappings below, so they are not repeated as custom:TMT <label>.
const CONSUMED_PROPERTIES = new Set(['Title', 'UserThreatDescription', 'InteractionString', 'StateInformation', 'Priority']);

type ElementRole = 'source' | 'target' | 'flow';
type ElementNames = Partial<Record<ElementRole, string>>;
type StatementFields = TmtTemplateFields & Pick<TemplateThreatStatement, 'customTemplate'>;
type ComposedStatement = { fields: StatementFields; warning?: string } | { reason: string };

const PLACEHOLDER = /\{(source|target|flow)\.name\}/gi;
const PLACEHOLDER_PART = /(\{(?:source|target|flow)\.name\})/i;
const MAPPINGS_BY_TYPE_ID = new Map(TMT_TEMPLATE_MAPPINGS.map((mapping) => [mapping.id, mapping]));
// A literal, so no '.tm7' content ever becomes a template.
const SINGLE_FIELD_TEMPLATE = '[threat_action]';
const GRAMMAR_FIELDS_SCHEMA = TemplateThreatStatementSchema.pick({
  threatSource: true, prerequisites: true, threatAction: true, threatImpact: true, impactedGoal: true, impactedAssets: true,
});

const roleOf = (placeholder: string) => placeholder.slice(1, placeholder.indexOf('.')).toLowerCase() as ElementRole;
const escapeRegExp = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// Returns undefined when a placeholder's element has no name or the result would exceed maxLength;
// the length is computed first so an untrusted name is never expanded into an oversized string.
const fillPlaceholders = (text: string, names: ElementNames, maxLength = SINGLE_FIELD_INPUT_MAX_LENGTH): string | undefined => {
  let unresolved = false;
  let length = text.length;
  text.replace(PLACEHOLDER, (placeholder: string) => {
    const name = names[roleOf(placeholder)];
    unresolved = unresolved || name === undefined;
    length += (name ?? '').length - placeholder.length;
    return placeholder;
  });
  if (unresolved || length > maxLength) {
    return undefined;
  }
  return text.replace(PLACEHOLDER, (placeholder: string) => names[roleOf(placeholder)] ?? '');
};

// TMT fills '{x.Name}' but can leave the lowercase '{x.name}' unfilled, so either form matches.
const matchesTemplate = (text: string | undefined, template: string, names: ElementNames): boolean => {
  if (!text) {
    return false;
  }
  const pattern = template.split(PLACEHOLDER_PART).map((part, index) => {
    if (index % 2 === 0) {
      return escapeRegExp(part);
    }
    const name = names[roleOf(part)];
    return name === undefined ? escapeRegExp(part) : `(?:${escapeRegExp(name)}|${escapeRegExp(part)})`;
  }).join('');
  return new RegExp(`^${pattern}$`).test(text.trim());
};

const fillMappingFields = (fields: TmtTemplateFields, names: ElementNames): TmtTemplateFields | undefined => {
  const filled: Record<string, string | string[] | undefined> = {};
  for (const [key, value] of Object.entries(fields)) {
    const values = (Array.isArray(value) ? value : [value]).map((v) => fillPlaceholders(v, names));
    const filledValues = values.filter((v): v is string => v !== undefined);
    if (filledValues.length !== values.length) {
      return undefined;
    }
    filled[key] = Array.isArray(value) ? filledValues : filledValues[0];
  }
  return filled as TmtTemplateFields;
};

// A curated mapping applies only to unedited knowledge-base text; anything else falls back with a warning.
// Lengths are checked on sanitized text, because the import boundary encodes '&', '<', and '>' before validating.
const composeStatement = (
  threat: TmtThreat,
  threatType: TmtThreatType | undefined,
  names: ElementNames,
  hasOverLongName: boolean,
): ComposedStatement => {
  const { Title: title, UserThreatDescription: description } = threat.properties;
  const mapping = threat.typeId ? MAPPINGS_BY_TYPE_ID.get(threat.typeId) : undefined;
  let fallbackCause = 'no curated template mapping matched its title and description';
  if (mapping && matchesTemplate(title, mapping.title, names) && matchesTemplate(description, mapping.template, names)) {
    const fields = fillMappingFields(mapping.fields, names);
    if (fields && GRAMMAR_FIELDS_SCHEMA.safeParse(sanitizeHtml(fields)).success) {
      return { fields };
    }
    fallbackCause = 'its curated template mapping exceeded a Threat Composer field limit';
  }
  const candidates: Array<[string, string | undefined]> = [
    ['description', description],
    ['title', title],
    ['short title', threatType?.shortTitle],
  ];
  for (const [label, text] of candidates) {
    const filled = text?.trim() ? fillPlaceholders(text.trim(), names) : undefined;
    if (filled && sanitizeHtml(filled).length <= SINGLE_FIELD_INPUT_MAX_LENGTH) {
      return {
        fields: { threatAction: filled, customTemplate: SINGLE_FIELD_TEMPLATE },
        warning: `TMT threat ${threat.id}: ${fallbackCause}, so its statement is the TMT ${label} as written`,
      };
    }
  }
  if (hasOverLongName) {
    return { reason: `No usable threat statement: a diagram element name it refers to exceeds ${SINGLE_FIELD_INPUT_MAX_LENGTH} characters.` };
  }
  return {
    reason: `No usable threat statement: no curated template mapping applies, and the description, title, and short title are missing, over the ${SINGLE_FIELD_INPUT_MAX_LENGTH}-character field limit, or name a diagram element that is not in the model.`,
  };
};

const buildThreatMetadata = (threat: TmtThreat, model: TmtModel, category: string | undefined): MetadataEntry[] => {
  const metadata: MetadataEntry[] = [];
  const usedKeys = new Set<string>();
  const add = (key: string, value: string | string[] | undefined) => {
    if (value === undefined || value === '' || (Array.isArray(value) && value.length === 0) || usedKeys.has(key)) {
      return;
    }
    metadata.push({ key, value });
    usedKeys.add(key);
  };

  if (category && STRIDE_LETTERS.has(category)) {
    add(METADATA_KEY_STRIDE, [category]);
  }
  const priority = threat.priority ? PRIORITY_BY_TMT.get(threat.priority) : undefined;
  if (priority) {
    add(METADATA_KEY_PRIORITY, priority);
  }

  add('custom:TMT Threat ID', String(threat.id));
  add('custom:TMT Title', threat.properties.Title);
  add('custom:TMT Category', category);
  add('custom:TMT State', threat.state);
  add('custom:TMT Description', threat.properties.UserThreatDescription);
  add('custom:TMT Interaction', threat.properties.InteractionString);
  add('custom:TMT Diagram', model.surfaces.find((surface) => surface.guid === threat.drawingSurfaceGuid)?.name);
  add('custom:TMT Justification', threat.properties.StateInformation);

  // Preserve every other non-empty property as custom:TMT <label> (KB label, else raw name);
  // on collision with an existing key, fall back to the raw property name to stay unique.
  for (const [name, value] of Object.entries(threat.properties)) {
    if (CONSUMED_PROPERTIES.has(name) || !value) {
      continue;
    }
    const labelKey = `custom:TMT ${model.knowledgeBase.propertyLabels[name] ?? name}`;
    add(usedKeys.has(labelKey) ? `custom:TMT ${name}` : labelKey, value);
  }
  return metadata;
};

const getMetadataLimitError = (metadata: MetadataEntry[]): string | undefined => {
  const overLongKey = metadata.find((entry) => entry.key.length > METADATA_KEY_MAX_LENGTH);
  if (overLongKey) {
    return `Metadata field name "${overLongKey.key}" is ${overLongKey.key.length} characters, exceeding the ${METADATA_KEY_MAX_LENGTH}-character limit.`;
  }
  if (metadata.length > METADATA_MAX_ENTRIES) {
    return `Threat has ${metadata.length} metadata fields, exceeding the ${METADATA_MAX_ENTRIES}-field limit.`;
  }
  const overLongValue = metadata.find((entry) => longestValueLength(entry) > METADATA_VALUE_MAX_LENGTH);
  if (overLongValue) {
    return `Metadata field "${overLongValue.key}" value is ${longestValueLength(overLongValue)} characters, exceeding the ${METADATA_VALUE_MAX_LENGTH}-character limit.`;
  }
  return undefined;
};

/**
 * Converts the threats of a parsed TMT model into Threat Composer threats, following the documented
 * '.tm7' -> Threat Composer mapping. A threat that cannot be faithfully imported (no resolvable
 * statement, or a field or field count over a size limit) is not silently dropped or
 * truncated: it is collected in 'unconvertible' with a clear reason for the import flow to present as
 * an abort/ignore decision. Softer issues (unknown state, non-STRIDE category, duplicate id) are
 * returned as non-blocking warnings on the threats that were converted.
 */
export const convertTmtThreats = (model: TmtModel): TmtThreatConversionResult => {
  const warnings: string[] = [];
  const unconvertible: TmtUnconvertibleThreat[] = [];
  const threats: TemplateThreatStatement[] = [];
  const usedNumericIds = new Set<number>();
  let nextAllocatedId = model.threats.reduce((max, threat) => Math.max(max, threat.id), 0) + 1;

  for (const threat of model.threats) {
    const threatType = threat.typeId ? model.knowledgeBase.threatTypes[threat.typeId] : undefined;
    const rawNames = [threat.sourceGuid, threat.targetGuid, threat.flowGuid].map((guid) => (guid ? model.elementNames[guid] : undefined));
    // A name longer than any field it could fill is unusable; dropping it early avoids expanding it.
    const [source, target, flow] = rawNames.map((name) => (name && name.length <= SINGLE_FIELD_INPUT_MAX_LENGTH ? name : undefined));
    const hasOverLongName = rawNames.some((name) => name !== undefined && name.length > SINGLE_FIELD_INPUT_MAX_LENGTH);

    const composed = composeStatement(threat, threatType, { source, target, flow }, hasOverLongName);
    if ('reason' in composed) {
      unconvertible.push({ id: threat.id, reason: composed.reason });
      continue;
    }
    const { statement, displayedStatement } = renderThreatStatement({ id: '', numericId: 0, ...composed.fields });
    if (!statement) {
      unconvertible.push({ id: threat.id, reason: 'No usable threat statement: the composed statement is empty.' });
      continue;
    }
    if (statement.length > STATEMENT_MAX_LENGTH) {
      unconvertible.push({
        id: threat.id,
        reason: `Threat statement is ${statement.length} characters, exceeding the ${STATEMENT_MAX_LENGTH}-character limit.`,
      });
      continue;
    }

    // Warnings gathered while building this threat are only committed if the threat is convertible.
    const threatWarnings: string[] = composed.warning ? [composed.warning] : [];

    let status = THREAT_STATUS_IDENTIFIED;
    if (threat.state) {
      const mapped = STATUS_BY_STATE.get(threat.state);
      if (mapped) {
        status = mapped;
      } else {
        threatWarnings.push(`Unknown TMT state '${threat.state}' for threat ${threat.id}; defaulted to identified`);
      }
    }

    const category = threatType?.category?.trim();
    if (category && !STRIDE_LETTERS.has(category)) {
      threatWarnings.push(`TMT category '${category}' for threat ${threat.id} is not a STRIDE letter; STRIDE omitted`);
    }

    const metadata = buildThreatMetadata(threat, model, category);
    const metadataLimitError = getMetadataLimitError(metadata);
    if (metadataLimitError) {
      unconvertible.push({ id: threat.id, reason: metadataLimitError });
      continue;
    }

    let numericId = threat.id;
    if (usedNumericIds.has(numericId)) {
      numericId = nextAllocatedId;
      nextAllocatedId += 1;
      threatWarnings.push(`Duplicate TMT threat id ${threat.id}; assigned numeric id ${numericId}`);
    }

    const candidate: TemplateThreatStatement = {
      id: crypto.randomUUID(),
      numericId,
      ...composed.fields,
      statement,
      displayedStatement,
      status,
      metadata,
    };

    // Validate the HTML-encoded form the import boundary stores, so any violation affects only this threat.
    const parsed = TemplateThreatStatementSchema.safeParse(sanitizeHtml(candidate));
    if (!parsed.success) {
      unconvertible.push({
        id: threat.id,
        reason: `Does not satisfy the Threat Composer threat schema: ${parsed.error.issues
          .map((issue) => `${issue.path.join('.') || 'value'}: ${issue.message}`)
          .join('; ')}.`,
      });
      continue;
    }

    usedNumericIds.add(numericId);
    threats.push(candidate);
    warnings.push(...threatWarnings);
  }

  return { threats, unconvertible, warnings };
};
