/** *******************************************************************************************************************
  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License").
  You may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 ******************************************************************************************************************** */
import { readFileSync } from 'fs';
import { join } from 'path';
import { parseTmtModel } from '.';

const fixture = (name: string) => readFileSync(join(__dirname, '../__fixtures__', name), 'utf-8');

describe('parseTmtModel - Sample_Threat_Model.tm7 (single DFD)', () => {
  const model = parseTmtModel(fixture('Sample_Threat_Model.tm7'));

  test('extracts the single non-empty drawing surface with its GUID and name', () => {
    expect(model.surfaces).toHaveLength(1);
    expect(model.surfaces[0]).toMatchObject({
      guid: 'd8c8aab1-5108-49c5-92a1-b214ba353477',
      name: 'Diagram 1',
      isEmpty: false,
    });
  });

  test('extracts all threat instances from the ThreatInstances dictionary', () => {
    expect(model.threats).toHaveLength(29);
    const threat = model.threats.find((t) => t.id === 7);
    expect(threat).toBeDefined();
    expect(threat?.drawingSurfaceGuid).toBe('d8c8aab1-5108-49c5-92a1-b214ba353477');
    expect(threat?.flowGuid).toBe('f367ac70-74ff-4ba1-abc4-0ac96e350448');
  });

  test('leaves empty model metadata undefined (name/owner are blank in this fixture)', () => {
    expect(model.metadata.threatModelName || undefined).toBeUndefined();
    expect(model.metadata.owner || undefined).toBeUndefined();
  });

  test('extracts a non-empty knowledge base (threat types and property labels)', () => {
    expect(Object.keys(model.knowledgeBase.threatTypes).length).toBeGreaterThan(0);
    expect(Object.keys(model.knowledgeBase.propertyLabels).length).toBeGreaterThan(0);
  });

  test('extracts DFD element names by GUID', () => {
    expect(model.elementNames['41cb799f-434b-4b35-bd8e-8970bb985ec9']).toBe('Generic External Interactor');
  });
});

describe.each([
  'Sample_Threat_Model.tm7',
  'Sample_Threat_Model_Multiple_DFDs.tm7',
  'ContosoCast Threat Model Fully Labeled with AI.tm7',
])('parseTmtModel - %s element names', (name) => {
  test('resolves the source, target, and flow of every threat to a name', () => {
    const model = parseTmtModel(fixture(name));
    const unresolved = model.threats.flatMap((t) => [t.sourceGuid, t.targetGuid, t.flowGuid])
      .filter((guid) => guid && !model.elementNames[guid]);
    expect(unresolved).toEqual([]);
  });
});

describe('parseTmtModel - Sample_Threat_Model_Multiple_DFDs.tm7 (multiple DFDs)', () => {
  const model = parseTmtModel(fixture('Sample_Threat_Model_Multiple_DFDs.tm7'));

  test('extracts all three surfaces in document order', () => {
    expect(model.surfaces.map((s) => s.name)).toEqual(['Diagram 1', 'Diagram 2', 'Diagram 3']);
  });

  test('extracts every threat instance', () => {
    expect(model.threats).toHaveLength(87);
  });
});

describe('parseTmtModel - threat detail', () => {
  const model = parseTmtModel(fixture('Sample_Threat_Model.tm7'));

  test('preserves the raw Properties bag, State and Priority for a threat', () => {
    const threat = model.threats.find((t) => t.id === 7);
    expect(threat).toBeDefined();
    expect(threat?.state).toBe('AutoGenerated');
    expect(threat?.priority).toBe('High');
    expect(Object.keys(threat?.properties ?? {})).toEqual(
      expect.arrayContaining(['Title', 'UserThreatDescription']),
    );
  });
});

const NS = 'http://schemas.datacontract.org/2004/07/ThreatModeling.Model';
const minimalModel = (inner: string, ns: string = NS) =>
  `<ThreatModel xmlns="${ns}">` +
  '<DrawingSurfaceList><DrawingSurfaceModel><Guid>11111111-1111-1111-1111-111111111111</Guid>' +
  '<Header>Empty Diagram</Header></DrawingSurfaceModel></DrawingSurfaceList>' +
  '<MetaInformation><ThreatModelName>My Model</ThreatModelName></MetaInformation>' +
  `${inner}</ThreatModel>`;
const validMinimal = minimalModel('<Version>4.3</Version>');

describe('parseTmtModel - minimal valid model', () => {
  const model = parseTmtModel(validMinimal);

  test('parses a minimal model and marks a surface with no elements as empty', () => {
    expect(model.surfaces).toEqual([
      { guid: '11111111-1111-1111-1111-111111111111', name: 'Empty Diagram', isEmpty: true },
    ]);
    expect(model.metadata.threatModelName).toBe('My Model');
    expect(model.threats).toEqual([]);
    expect(model.elementNames).toEqual({});
  });

  test('returns surface names without surrounding whitespace', () => {
    const padded = parseTmtModel(validMinimal.replace('<Header>Empty Diagram</Header>', '<Header>  Empty Diagram \n</Header>'));
    expect(padded.surfaces[0].name).toBe('Empty Diagram');
  });

  test('keeps an element named by an untrusted __proto__ GUID as plain data', () => {
    const xml = `<ThreatModel xmlns="${NS}"><DrawingSurfaceList><DrawingSurfaceModel><Guid>s</Guid><Header>D</Header>`
      + '<Borders><KeyValueOfguidanyType><Key>__proto__</Key><Value><Guid>__proto__</Guid><Properties>'
      + '<anyType><DisplayName>Name</DisplayName><Value>Evil</Value></anyType></Properties></Value>'
      + '</KeyValueOfguidanyType></Borders></DrawingSurfaceModel></DrawingSurfaceList><Version>4.3</Version></ThreatModel>';
    const parsed = parseTmtModel(xml);
    expect(parsed.elementNames.__proto__).toBe('Evil');
    expect(({} as Record<string, unknown>).Evil).toBeUndefined();
    expect(Object.getPrototypeOf(parsed.elementNames)).toBeNull();
  });
});

describe('parseTmtModel - rejects invalid input (imports nothing)', () => {
  test('empty input', () => {
    expect(() => parseTmtModel('')).toThrow('Empty');
  });

  test('oversized input', () => {
    expect(() => parseTmtModel(validMinimal, { maxChars: 10 })).toThrow('maximum allowed size');
  });

  test('DOCTYPE declaration', () => {
    expect(() => parseTmtModel(`<!DOCTYPE x>${validMinimal}`)).toThrow('DOCTYPE or ENTITY');
  });

  test('ENTITY declaration (XXE payload)', () => {
    const xxe = `<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>${validMinimal}`;
    expect(() => parseTmtModel(xxe)).toThrow('DOCTYPE or ENTITY');
  });

  test('wrong root element', () => {
    expect(() => parseTmtModel(`<NotThreatModel xmlns="${NS}"><Version>4.3</Version></NotThreatModel>`)).toThrow('Not a TMT');
  });

  test('foreign namespace', () => {
    expect(() => parseTmtModel(minimalModel('<Version>4.3</Version>', 'http://evil.example/ns'))).toThrow('Not a TMT');
  });

  test('malformed XML', () => {
    expect(() => parseTmtModel(`<ThreatModel xmlns="${NS}"><Version>4.3</Version><Unclosed></ThreatModel>`)).toThrow('Malformed');
  });

  test('absent version', () => {
    expect(() => parseTmtModel(minimalModel(''))).toThrow('Unsupported');
  });

  test('empty version', () => {
    expect(() => parseTmtModel(minimalModel('<Version/>'))).toThrow('Unsupported');
  });

  test('unsupported version 4.2', () => {
    expect(() => parseTmtModel(minimalModel('<Version>4.2</Version>'))).toThrow('Unsupported');
  });

  test('threat with a non-integer Id', () => {
    const xml = minimalModel(
      '<Version>4.3</Version><ThreatInstances><KeyValueOfstringThreatX><Key>k</Key>' +
        '<Value><Id>not-a-number</Id></Value></KeyValueOfstringThreatX></ThreatInstances>',
    );
    expect(() => parseTmtModel(xml)).toThrow('valid integer Id');
  });
});

describe('parseTmtModel - hardening', () => {
  test('a malicious __proto__ property key does not pollute Object.prototype', () => {
    const xml = minimalModel(
      '<Version>4.3</Version><ThreatInstances><KeyValueOfstringThreatX><Key>k</Key><Value><Id>1</Id>' +
        '<Properties><KeyValueOfstringstring><Key>__proto__</Key><Value>polluted</Value></KeyValueOfstringstring></Properties>' +
        '</Value></KeyValueOfstringThreatX></ThreatInstances>',
    );
    const model = parseTmtModel(xml);
    expect(({} as Record<string, unknown>).polluted).toBeUndefined();
    expect(Object.keys(model.threats[0].properties)).toContain('__proto__');
  });
});
